[build-system]
requires = ["setuptools>=68"]
build-backend = "setuptools.build_meta"

[project]
name = "elo-api"
version = "0.1.0"
description = "ELO API based on Python with FastAPI."
readme = "README.md"
requires-python = ">=3.10"
dependencies = [
    "fastapi==0.115.12",
    "uvicorn==0.34.2",
]

[project.optional-dependencies]
dev = [
    "httpx==0.28.1",
    "pytest==8.3.5",
]

[tool.pytest.ini_options]
testpaths = ["tests"]
